name = "Bit Rounding"

[[codec]]
name = "bitround"
import = "numcodecs_wasm_bit_round.BitRound"
kind = "lossy"

[codec.parameters]
keepbits = { type = "int", value = 9 }

[[codec]]
name = "zlib"
import = "numcodecs_wasm_zlib.Zlib"
kind = "binary-lossless"

[codec.parameters]
level = { type = "int", value = 6 }
