name = "Bit Rounding + PCodec"

[[codec]]
name = "bitround"
import = "numcodecs_wasm_bit_round.BitRound"
kind = "lossy"

[codec.parameters]
keepbits = { type = "int", value = 9 }

[[codec]]
name = "pco"
import = "numcodecs_wasm_pco.Pco"
kind = "binary-lossless"

[codec.parameters]
level = { type = "int", value = 8 }
mode_spec = { type = "str", value = "auto" }
