name = "Linear Quantization"

[[codec]]
name = "linearquantize"
import = "fcbench.codecs.LinearQuantize"
kind = "lossy"

[codec.parameters]
dtype = { type = "str", value = "float32" }
bits = { type = "int", value = 9 }

[[codec]]
name = "zlib"
import = "fcbench.codecs.Zlib"
kind = "binary-lossless"

[codec.parameters]
level = { type = "int", value = 6 }
