name = "ZFP"

[[codec]]
name = "reshape"
import = "numcodecs_wasm_swizzle_reshape.SwizzleReshape"
kind = "binary-lossless"

[codec.parameters]
# collapse into ((realization, time,), (vertical,), (latitude,), (longitude,))
axes = { type = "json", value = "[[0, 1], [2], [3], [4]]" }

[[codec]]
name = "zfp"
import = "numcodecs_wasm_zfp.Zfp"
kind = "lossy"

[codec.parameters]
mode = { type = "str", value = "fixed-accuracy" }
tolerance = { type = "float", value = 0.01 }
