[project]
name = "climatebenchpress.compressor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cf-xarray==0.10.0",
    "dask==2024.12.0",
    "field-compression-benchmark==0.0.15",
    "xarray==2024.11.0",
    "zarr==2.18.3",
]

[dependency-groups]
dev = ["ipykernel~=6.29", "ruff~=0.8"]
